# This is a basic workflow to help you get started with Actions

name: Git_Hub_Action

# Controls when the workflow will run
on:  
  push:
    branches: 
      - master

jobs:

  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run: echo "Hello World from Testing Job" 
  
  
  my_deploy:
    runs_on: ubuntu-latest
    
    steps  :
     - name: Print Hello Message
       run : echo "Hello World from Deploy Job"
