#

name: Bot-aotomatication


on:
  push:
   branches: 
     - master

jobs:
# Запус, авторизация Docker Compose
  start_Docker_compos:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker-compose build
        docker-compose push

# Проверка статуса БД
  check_database:
      runs-on: ubuntu-latest
      needs: [start_Docker_compos]
    
      steps:
      - name: Check if database is running
        run: | 
         docker-compose ps -q database | xargs docker inspect -f '{{.State.Running}}' 
        
# Запуск main
  start_main:
      runs-on: ubuntu-latest
      needs: [start_Docker_compos, check_database]

      steps:
        - name: Run main application
          run : docker-compose up main
      
        
    
    
