#

name: Bot-aotomatication


on:
  push:
   branches: 
     - master

jobs:
  start_Docker_compos:
    runs-on: ubuntu-latest

# Запус, авторизация Docker Compose
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker-compose build
        docker-compose push

# Проверка статуса БД
    - name: Check if database is running
      run: |
        docker-compose ps -q database | xargs docker inspect -f '{{.State.Running}}'
        
# Запуск main
    - name: Run main application
      run: docker-compose up main
    
    
